---
- name: deploy .war from Ansible WS
  hosts: devlinux:qalinux
  user: velocity
  become: yes
  connection: ssh

  tasks:
  - name: install Java
    ansible.builtin.yum:
      name: java-21-amazon-corretto.x86_64
      state: present

  - name: Install tomcat 10
    ansible.builtin.get_url:
      url: "{{https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.60/bin/apache-tomcat-10.1.60.zip}}"
      dest: "/mnt/"

  - name: Extract Tomcat
    ansible.builtin.unarchive:
        src: "/mnt/apache-tomcat-10.1.60.zip"
        dest: "/mnt/"

  - name: permissions to tomcat 
    ansible.builtin.file:
      path: /mnt/apache-tomcat-10.1.60/bin/startup.sh
      mode: '0755'

  - name: deploy
    ansible.builtin.copy:
      src: "/mnt/project/target/LoginWebApp.war"
      dest: "/mnt/apache-tomcat-10.1.60/webapps/"

  - name: start tomcat
    ansible.builtin.command:
      cmd: "/mnt/apache-tomcat-10.1.60/bin/startup.sh"
